workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.pe.seller"
      flutter: stable
      xcode: latest

    scripts:
      - name: Set iOS minimum deployment target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install || true
          sed -i '' "s/# platform :ios, '12.0'/platform :ios, '14.0'/" ios/Podfile || true
          sed -i '' "s/platform :ios, '12.0'/platform :ios, '14.0'/" ios/Podfile || true
          pod install --repo-update
      - name: Build iOS App
        script: |
          flutter build ipa --release \
            --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: "J2BUVTG7N7"
        issuer_id: "6e3ba3e7-a936-45fb-a6dd-148932e76eb1"
        submit_to_testflight: true
